---

- hosts: docker-hosts

  vars:
    docker_registry: 192.168.0.17:5000

  tasks:
    # Setup docker on the docker hosts
    - include: provision_docker_hosts.yml

      become: true


# End docker-hosts section

- hosts: loadbalancers

  tasks:
    - name: Ensure HAProxy is installed and up to date
      become: true
      apt:
        name: haproxy
        state: latest
        update_cache: yes

    - name: Configure haproxy cnf file with hosts
      become: true
      template:
        src: haproxy/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Enable haproxy
      # toggles the ENABLED flag in /etc/default/haproxy
      become: true
      replace:
        dest: /etc/default/haproxy
        regexp: "ENABLED=0"
        replace: "ENABLED=1"
      notify: restart haproxy

  handlers:
    - name: restart haproxy
      become: true
      service:
        name: haproxy
        state: restarted
        enabled: true
